Refactor/neon/settings
nextcloud/neon pull request #1012
Opened 2023-10-23 11:02 UTC by Leptopoda

handles the design part of #849
Changes to existing platforms:
- the visual density of the Settings will be higher on Linux than before
- `SelecOption`s will now be handled in popup dialogs as it is common on m3
- SettingsCategories will no longer be separated by a divider to match the m3 design 

The m3 docs themselves do not mention the modifications I made but I got inspired by the system settings on stock android

The cupertino design is better than before but not final yet.

2023-10-29 15:54 UTC, Leptopoda commented
I think that the entire idea of a separate `SettingsListTile` is bad.
Can we just remove it and provide it and provide normal widgets and helpers to style custom ones?

2023-10-29 19:48 UTC, Leptopoda reviewed
https://github.com/nextcloud/neon/pull/1030#discussion_r1372870104

So we don't forget those refactors

2023-11-02 08:47 UTC, provokateurin requested changes
Select options are a bit broken because the currently selected value is not shown in the tile. Initially I thought you forgot to add it (I checked how it works in the settings on my phone) but it looks like you added it and it's just not working.

Is there an easy way to test the cupertino layout?

2023-11-02 08:47 UTC, provokateurin commented on .cspell/dart_flutter.txt
> +Cupertino
All words in the dictionaries are lowercase

2023-11-02 08:47 UTC, provokateurin commented on packages/neon/neon/lib/src/settings/widgets/settings_category.dart
> +    switch (theme.platform) {
Should use isCupertino()

2023-11-02 08:48 UTC, provokateurin requested changes
packages/app/pubspec.lock is not updated

2023-11-02 08:51 UTC, Leptopoda commented
> Is there an easy way to test the cupertino layout?

Just specify the platform in the theme. There are still bigger issues with the scaffold background color mismatching but as iOS is still a WIP I will address them separately.
```dart
    return ThemeData(
        platform: TargetPlatform.iOS,
        [...]
      );
```

2023-11-02 08:53 UTC, Leptopoda commented
Also because of some license issues with the apple font you will not be able to see the `+` icon in the add account tile unless you run it on iOS itself.

2023-11-02 08:53 UTC, Leptopoda commented
Also because of some license issues with the apple font you will not be able to see the `+` icon in the add account tile unless you run it on iOS itself.

2023-11-02 09:06 UTC, provokateurin commented
> Also because of some license issues with the apple font you will not be able to see the + icon in the add account tile unless you run it on iOS itself.

lol what. fucking apple...

2023-11-02 10:12 UTC, provokateurin approved these changes

2023-11-02 12:36 UTC, merged