perf(neon): do not use the spread operator for building lists
nextcloud/neon pull request #1094
Opened 2023-11-03 14:07 UTC by Leptopoda

Fixes: #696

2023-11-03 14:15 UTC, provokateurin commented
Draft is on purpose?

2023-11-03 14:18 UTC, Leptopoda commented
This time yes.
I made the NeonProgressIndicator conditional and wanted to remove the `visible` property in a followup but noticed that this would cause flickering when it gets removed.
I already reverted most of them locally and we'll need to wait for #800 to properly change this.

2023-11-03 22:30 UTC, Leptopoda commented
Oh totally forgot to mark it as ready for review :woman_facepalming:

2023-11-16 20:30 UTC, provokateurin requested changes
Oops I forgot about this PR

2023-11-16 20:30 UTC, provokateurin commented on packages/neon/neon/lib/src/pages/login.dart
> +                  if (branding.showLoginWithNextcloud)
Duplicate condition, better use a generator function for the whole thing

2023-11-16 20:30 UTC, provokateurin commented on packages/neon/neon_news/lib/dialogs/add_feed.dart
Duplicate condition -> generator function

2023-11-16 20:30 UTC, provokateurin commented on packages/neon/neon_news/lib/pages/article.dart
Duplicate condition -> generator function

2023-11-16 20:30 UTC, provokateurin commented on packages/neon/neon_notes/lib/dialogs/create_note.dart
Duplicate condition -> generator function

2023-11-16 20:30 UTC, provokateurin commented on packages/neon/neon_notes/lib/widgets/notes_view.dart
Duplicate condition -> generator function

2023-11-16 21:25 UTC, Leptopoda commented
Thanks for the feedback.
I'll touch this PR up after all the dynamite work I'm currently working on.

2023-12-28 12:18 UTC, Leptopoda commented
Closing this one.
There is no point in rebasing it.

2023-12-28 12:18 UTC, closed without merging