fix(nextcloud): Fix WebDAV path construction
nextcloud/neon pull request #1096
Opened 2023-11-03 15:07 UTC by provokateurin

Fixes https://github.com/nextcloud/neon/issues/1045

2023-11-03 16:11 UTC, Leptopoda requested changes

2023-11-03 16:11 UTC, Leptopoda commented on packages/nextcloud/lib/src/webdav/file.dart
> +  late final bool isDirectory = (isCollection ?? false) || path.pathSegments.last == '';
```suggestion
  late final bool isDirectory = (isCollection ?? false) || path.pathSegments.last.isEmpty;
```

2023-11-03 16:11 UTC, Leptopoda commented on packages/nextcloud/lib/src/webdav/file.dart
> +  late final String name = path.pathSegments.where((final s) => s != '').lastOrNull ?? '';
```suggestion
  late final String name = path.pathSegments.where((final s) => s.isNotEmpty).lastOrNull ?? '';
```

2023-11-03 16:11 UTC, Leptopoda commented on packages/nextcloud/lib/src/webdav/client.dart
> +    return baseURL.replace(pathSegments: segments.where((final s) => s != ''));
```suggestion
    return baseURL.replace(pathSegments: segments.where((final s) => s.isNotEmpty));
```

2023-11-03 16:11 UTC, Leptopoda commented on packages/nextcloud/test/webdav_test.dart
> +  }
Please wrap this in a group

2023-11-03 16:14 UTC, Leptopoda commented
Without knowing how the `PathUri` is going to look I expect it to address the silly `isEmpty` stuff.
The `pathSegments` getter should by default only return relevant segments (that are not empty) and I'd like helper methods like `isDirectory`.

I already think you did so but just wanted to make it clear from the start.

2023-11-03 16:34 UTC, provokateurin commented
Yes I added some convenience features in the PathUri to remove duplicate and ugly code.

2023-11-03 22:32 UTC, Leptopoda approved these changes
LGTM
Can't wait for the coming changes

2023-11-03 22:33 UTC, provokateurin commented
Let's wait for the testing by @vauvenal5 to confirm this fixes the problems.

2023-11-04 08:44 UTC, vauvenal5 commented
Did a quick test, LGTM. :+1:

2023-11-04 09:02 UTC, merged