chore(nextcloud): Update server specs
nextcloud/neon pull request #1121
Opened 2023-11-06 15:33 UTC by provokateurin

API should be stable now for the 28 release.

2023-11-06 16:06 UTC, Leptopoda approved these changes
Nothing obvious that looks wrong

2023-11-06 16:20 UTC, provokateurin commented
I didn't update to the latest version and committed the wrong stuff.

2023-11-06 16:32 UTC, Leptopoda requested changes
Rejecting for now until I have more time to properly test these changes.

2023-11-06 16:32 UTC, Leptopoda commented on packages/nextcloud/lib/src/api/user_status.openapi.json
> +                                                        }
This will probably need to be patched to an anyOf.
I think it was also broken before as `{}` just matches anything.

2023-11-06 16:49 UTC, provokateurin commented
I can also put this patch into a separate PR if you think that's better.

2023-11-07 10:13 UTC, Leptopoda commented
I haven't looked into it but I think we should unit test all patched endpoints.
Do you think this is possible to enforce in CI with some regex magic?

2023-11-07 10:15 UTC, provokateurin commented
It would be possible to detect these cases somehow, but it's a lot of effort to implement and we should really just fix dynamite. Besides that I don't expect many new of these cases so it's not like it requires constant attention to not break. Just be careful when reviewing new/updated specs.

2023-11-07 10:23 UTC, Leptopoda commented
I didn't mean to find the oneOf/anyOf bugs but a regex that ensures that all patched endpoints have unit tests.

2023-11-07 10:24 UTC, Leptopoda approved these changes
Unit tests for the patched endpoints would be great but looks good

2023-11-07 10:34 UTC, provokateurin commented
I'd say increasing the test coverage is one overall goal. I don't think adding tests for these particular cases is more helpful than testing other endpoints which don't have this problem.

2023-11-07 10:34 UTC, merged