feat(nextcloud_test): Use presets for running tests
nextcloud/neon pull request #1190
Opened 2023-11-27 21:08 UTC by provokateurin

Adds the infrastructure for https://github.com/nextcloud/neon/issues/571

2023-11-27 21:18 UTC, provokateurin commented
Best to review with https://github.com/nextcloud/neon/pull/1190/files?w=1 to ignore annoying whitespace diff.

2023-11-28 08:13 UTC, provokateurin commented
@Leptopoda Added all presets for app versions that are compatible with 27.1.

2023-11-28 11:23 UTC, Leptopoda requested changes
I fundamentally dislike these changes.
I can no longer run the tests from within the IDE. I agree that this is a minor disadvantage compared to what this PR brings but still something I'd like to be handled differently.

I'd rather make `nextcloud_test` an independent testing package like `flutter_test` (https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/test_compat.dart) by utilizing `test_api` or `test_core` if needed.

We should only need to setup a custom [`Declarer`](https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/declarer.dart) and register all the groups to it.

2023-11-28 11:28 UTC, provokateurin commented on packages/nextcloud_test/lib/src/presets.dart
> +void presets(final String presetGroup, final dynamic Function(Preset preset) body) {
The tests need to be able to configure some things when creating the client like the username, so we can't do it automatically. We could do it for the container though if you like it.

2023-11-28 11:30 UTC, provokateurin commented on packages/nextcloud_test/lib/src/presets.dart
> +        .map((final f) => Version.parse(PathUri.parse(f.path).name));
I agree that it is not pretty, but using glob syntax feels very wrong in this case.

2023-11-28 11:30 UTC, Leptopoda commented on packages/nextcloud_test/lib/src/presets.dart
> +void presets(final String presetGroup, final dynamic Function(Preset preset) body) {
Ah I didn't think about this.
I don't care and we can leave it as is if you want.

2023-11-28 11:38 UTC, Leptopoda commented
> They behave exactly the same as before.

Nope. Using either of the red marked shortcuts to run a single test result in an error similar to:
```sh
No tests match regular expression "^dashboard Get widget items v1( \(variant: .*\))?$".
```

![Screenshot_20231128_123517](https://github.com/nextcloud/neon/assets/25266387/9cbc453c-6d84-433c-b760-7f0bb07a5b28)

Running an entire file (by hitting the `run` for the main) results in:
```sh
Exception: Missing docker image ghcr.io/nextcloud/neon/dev:server-27.1.3. Please build it using ./tool/build-dev-container.sh
package:nextcloud_test/src/docker_container.dart 33:7  DockerContainer.create
===== asynchronous gap ===========================
test/core_test.dart 14:23                              main.<fn>.<fn>.<fn>
LateInitializationError: Local 'container' has not been initialized.
dart:_internal             LateError._throwLocalNotInitialized
test/core_test.dart 17:24  main.<fn>.<fn>.<fn>
```

2023-11-28 11:41 UTC, Leptopoda commented on packages/nextcloud_test/lib/src/presets.dart
> +        .map((final f) => Version.parse(PathUri.parse(f.path).name));
:woman_shrugging:

2023-11-28 11:46 UTC, provokateurin commented
> Nope. Using either of the red marked shortcuts to run a single test result in an error similar to:

Ok I never use it, maybe there is a way to fix it.

> Running an entire file (by hitting the run for the main) results in:

This is correct, the names of the images have changed so you need to build them first.

2023-11-28 12:41 UTC, provokateurin commented
In IntelliJ I can still run the tests just fine, so it might be a problem with the VScode plugin?

2023-11-28 15:55 UTC, provokateurin commented
Since the IDE debugging seems to be broken only in VScode and is probably not our fault I would like to ignore it for now (and open an issue about it to fix it later).

2023-11-28 16:16 UTC, Leptopoda approved these changes
Let's move on.
I still think that the ide issue must be fixed in the near future.

2023-11-28 16:19 UTC, merged