fix(dynamite): Fix nullable someOf parameters
nextcloud/neon pull request #1272
Opened 2023-12-11 14:03 UTC by Leptopoda

#1256

2023-12-11 15:33 UTC, provokateurin requested changes

2023-12-11 15:33 UTC, provokateurin commented on packages/dynamite/dynamite_end_to_end_test/test/parameters_test.dart
> +    });
Please also test that it works with a string.

2023-12-11 15:34 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +        }
Please add a comment that explains why this is needed.

2023-12-12 11:52 UTC, Leptopoda commented
I think that it's probably easier to just call serialize (and not encode) on the typeresult and let the uri template handle the rest #1097.
I'll give it a try.

2023-12-12 15:36 UTC, provokateurin commented
That sounds good yeah

2023-12-12 15:45 UTC, provokateurin commented
yet another problem related to parameter serialization: pattern checking does not work on string values. I would argue it is useless because it is an enum already, but it is a valid spec and also happens to appear in Talk.

2023-12-12 15:47 UTC, Leptopoda commented
Pattern checking requires a bigger makeover.
Can you report an example spec to #1247?
Or open a new issue and mention it from there.

2023-12-12 16:00 UTC, provokateurin commented
I commented on the issue, but I feel like the problem is just the parameter serialization. The value needs to be serialized before checking the pattern (would be at least one way to fix it).

2023-12-16 17:19 UTC, Leptopoda commented
Still bases on #1292

2023-12-16 17:20 UTC, provokateurin approved these changes

2023-12-17 10:34 UTC, merged