refactor(neon_framework): introduce storage library
nextcloud/neon pull request #1554
Opened 2024-01-30 15:12 UTC by Leptopoda

first cleanup step towards #1538

2024-01-31 17:19 UTC, provokateurin requested changes
I don't like that often the class and file names don't match (not only the ones I mentioned).

2024-01-31 17:19 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/single_value_store.dart
Either the file should be called key_value_storage.dart or the class should be called SingleValueStore.

2024-01-31 17:19 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/request_cache.dart
The file and class names should be aligned.

2024-01-31 18:22 UTC, Leptopoda commented
I already had these changes locally.
I put it into a separate commit to keep the history sorta readable.

2024-02-01 08:35 UTC, provokateurin requested changes

2024-02-01 08:35 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/storage_manager.dart
> +  void _checkInitialized() {
Maybe `_assertInitialized`?

2024-02-01 08:35 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/request_cache.dart
> +        'Cache has not been set up yet. Please make sure Cache.init() has been called before and completed.',
```suggestion
        'Cache has not been set up yet. Please make sure DefaultRequestCache.init() has been called before and completed.',
```

2024-02-01 10:49 UTC, provokateurin approved these changes

2024-02-01 10:58 UTC, merged