refactor(neon_framework,neon_files): Make all Blocs only use built_value types
nextcloud/neon pull request #1643
Opened 2024-02-23 13:18 UTC by provokateurin

2024-02-23 19:17 UTC, Leptopoda requested changes

2024-02-23 21:28 UTC, provokateurin commented on packages/neon/neon_files/lib/src/widgets/browser_view.dart
> +                  input: filesSnapshot.data?.sublist(1).toList(),
Nope it doesn't and sort_box (and to an extend SortBoxBuilder) don't support BuiltList.

2024-02-23 21:28 UTC, provokateurin commented on packages/neon_framework/lib/src/blocs/timer.dart
Yeah I also stumbled over this when I refactored this bloc. I'll revert the changes to this bloc.

2024-02-23 21:55 UTC, provokateurin commented on packages/neon/neon_files/lib/src/widgets/browser_view.dart
> +                  input: filesSnapshot.data?.sublist(1).toList(),
https://pub.dev/documentation/built_collection/latest/built_collection/BuiltList/sublist.html

2024-02-24 08:57 UTC, Leptopoda approved these changes

2024-02-24 09:33 UTC, merged