feat(dynamite_runtime): add DynamiteRequest
nextcloud/neon pull request #1707
Opened 2024-03-04 18:12 UTC by Leptopoda

The last remaining piece of #1580

2024-03-06 11:23 UTC, provokateurin commented
Shouldn't it be possible now to put the serializer into the request? Or do you think that mixes the layers too much?

2024-03-06 11:25 UTC, Leptopoda commented
Do you mean similar to the validStatuses?

I think this is to much mixing. Although I have to admit that the validStatuses shouldn't be there either

2024-03-06 11:26 UTC, provokateurin commented
Yeah, and I somewhat agree that the validation should not be in the request.

2024-03-06 11:29 UTC, Leptopoda commented
So should we move the status code matching into the serializer?
Let it throw if the encountered status code is not valid?

2024-03-06 11:30 UTC, Leptopoda commented
This might also make sense long term if we want to allow different response schemas per status code.
I don't know how this would look in detail but it's more fitting there.

2024-03-06 11:32 UTC, provokateurin commented
That sounds good and should help with supporting multiple status codes :+1:

2024-03-08 23:29 UTC, provokateurin requested changes

2024-03-08 23:29 UTC, provokateurin commented on packages/dynamite/dynamite_runtime/lib/src/client/request.dart
> +  }
This is now part of the serializer, please remove

2024-03-09 07:18 UTC, provokateurin requested changes

2024-03-09 07:18 UTC, provokateurin commented on packages/neon_framework/lib/src/utils/request_manager.dart
> +          final response = await account.client.send(request);
Has to be sendWithCookies

2024-03-09 07:30 UTC, provokateurin approved these changes

2024-03-09 10:00 UTC, merged