refactor(neon_framework): adjust request cache schema
nextcloud/neon pull request #1741
Opened 2024-03-10 18:15 UTC by Leptopoda

Signed-off-by: Nikolas Rimikis <leptopoda@users.noreply.github.com>

2024-03-10 18:23 UTC, provokateurin requested changes

2024-03-10 18:23 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/request_cache.dart
> +          // breaking change should remove all non breaking migrations before it.
The comment is better placed before the transaction to explain what the whole onUpgrade method does.

2024-03-10 18:23 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/request_cache.dart
> +            parameters?.expires?.millisecondsSinceEpoch,
Should be seconds

2024-03-10 18:23 UTC, provokateurin commented on packages/neon_framework/lib/src/utils/date_time.dart
> +  /// 1970-01-01T00:00:00Z + [secondsSinceEpoch] s in the given
The seconds part needs be in front of the Z

2024-03-10 18:23 UTC, provokateurin commented on packages/neon_framework/test/persistence_test.dart
> +        expires: DateTimeUtils.fromSecondsSinceEpoch(DateTime.now().secondsSinceEpoch),
To achieve second precision the expect calls should be split.

2024-03-10 22:02 UTC, provokateurin requested changes

2024-03-10 22:02 UTC, provokateurin commented on packages/neon_framework/lib/src/utils/date_time.dart
Use https://pub.dev/packages/dart_date instead

2024-03-10 22:15 UTC, Leptopoda commented on packages/neon_framework/lib/src/storage/request_cache.dart
> +	"account"	TEXT NOT NULL,
broken formatting

2024-03-10 22:15 UTC, provokateurin requested changes

2024-03-10 22:15 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/request_cache.dart
> +      expires: expires != null ? DateTimeUtils.fromSecondsSinceEpoch(expires) : null,
`isUtc: true` missing (before this change as well)

2024-03-10 22:41 UTC, provokateurin commented on packages/neon_framework/lib/src/utils/date_time.dart
Ok no, it adds a dependency on intl which we don't want.

2024-03-10 22:41 UTC, Leptopoda commented on packages/neon_framework/lib/src/utils/date_time.dart
We decided not to use it to avoid the dependency on intl

2024-03-15 12:44 UTC, provokateurin reviewed
LGTM

2024-03-15 12:44 UTC, provokateurin commented on packages/neon_framework/lib/src/storage/request_cache.dart
> +	"value"   BLOB NOT NULL,
Shouldn't the blob thing be done separately as it has nothing to do with the account column?

2024-03-15 15:51 UTC, Leptopoda commented
Yep that was intentional.
I'll put it in a separate PR

2024-03-15 20:09 UTC, provokateurin approved these changes

2024-03-15 23:26 UTC, merged