feat(neon_talk): Show user status on room page
nextcloud/neon pull request #1788
Opened 2024-03-17 14:31 UTC by provokateurin

Instead of using the room that is passed to the widget the room of the bloc should be used because it will be updated on refresh. In case the room avatar would change it will be correctly reflected now while previously the room page had to be closed, the room list reloaded and the room page opened again.

2024-03-17 14:36 UTC, Leptopoda approved these changes
Can we test this in a meaningful way?

2024-03-17 14:39 UTC, provokateurin commented
If we add tests to the page surely. Ideally we shouldn't only test individual widgets but whole pages.

2024-03-17 14:40 UTC, Leptopoda requested changes
In that case please do so

2024-03-17 17:11 UTC, provokateurin commented
I'm not sure how to actually test it because I'd want to mock the bloc, but it gets created inside the page state so it can be disposed correctly. Either the bloc creation is moved outside the widget or we make the factory mockable somehow.

2024-03-27 23:36 UTC, provokateurin commented
@Leptopoda can we just merge this? I don't think I will have the time to fix this soon.

2024-03-28 07:40 UTC, Leptopoda approved these changes

2024-03-28 08:19 UTC, merged