feat(neon_lints): add avoid_exports lint rule
nextcloud/neon pull request #1836
Opened 2024-03-29 10:37 UTC by Leptopoda

Towards: #1764

2024-03-29 10:41 UTC, provokateurin requested changes
Please add a test and also check if the meta dependency can be removed from the packages.

2024-03-29 10:46 UTC, Leptopoda commented
How should I test this?
The lint rule is disabled in the framework package.

2024-03-29 10:48 UTC, provokateurin commented
Would it work to add an example subpackage to neon_lints and move all the tests to it?

2024-04-01 13:58 UTC, provokateurin approved these changes

2024-04-01 14:25 UTC, merged