fix(dynamite): json schema referenec resolving
nextcloud/neon pull request #1953
Opened 2024-04-22 17:48 UTC by Leptopoda

I did not find a better solution yet.
In theory this already allows us to fetch schemas fro other sources like local filesystem or remote servers.
I did not observe any performance penalty.

Towards: #933

2024-04-23 07:53 UTC, provokateurin requested changes
Could this have some tests? I see that it is not breaking anything because none of the generated code has changed, but that is no guarantee it won't break in the future.

2024-04-23 07:53 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/models/openapi/schema.dart
> +      throw StateError('Referenced schema can only be built when a ref is present');
```suggestion
      throw StateError(r'Referenced schema can only be built when a $ref is present');
```

2024-04-23 07:53 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/models/openapi/schema.dart
> +  Schema buildRef(Map<String, dynamic> json) {
```suggestion
  Schema resolveRef(Map<String, dynamic> json) {
```
I think this better reflects what it does. The ref isn't built, the ref is resolved and then the schema for it is built

2024-04-24 08:07 UTC, Leptopoda commented
We already had the e2e tests for this but I added some directly dynamite nevertheless

2024-04-24 08:16 UTC, provokateurin approved these changes

2024-04-24 08:17 UTC, provokateurin commented
Commit message has a typo and should be `fix(dynamite): json schema reference resolving`

2024-04-24 09:00 UTC, merged