feat: Added swipe-to-dismiss #2158
nextcloud/neon pull request #2241
Opened 2024-07-04 15:50 UTC by satvik2131

## Implemented swipe-to-dismiss feature in : 
1. Neon News 
   - Articles (swipe to mark read/unread)
   - Folders
   - Feeds

2. Neon Notifications 
3. Neon notes

2024-07-04 16:00 UTC, provokateurin requested changes

2024-07-04 16:00 UTC, provokateurin commented on packages/neon/neon_news/lib/src/widgets/folders_view.dart
> +                    if (action case NewsFolderAction.rename) {
Revert

2024-07-04 16:03 UTC, provokateurin commented
Thanks for the work btw :)

2024-07-04 16:05 UTC, satvik2131 commented
> Thanks for the work btw :)

most welcome , will be updating the changes soon, and btw you are literally very active , thanks for the feedback and guidance :)

2024-07-04 16:29 UTC, satvik2131 commented on packages/neon/neon_news/lib/src/widgets/feeds_view.dart
> +                    // ),
should I revert the changes , sorry , I didn't get it properly ?

2024-07-04 16:31 UTC, provokateurin commented on packages/neon/neon_news/lib/src/widgets/feeds_view.dart
> +                    // ),
Ah the context is too wide. Only the commented out code should be reverted

2024-07-04 17:38 UTC, provokateurin approved these changes
Thank you so much!
You need to fix the DCO and please name the commit something like `refactor(neon_news,neon_notes,neon_notifications): Replace long press actions with swipe-to-dismiss`

2024-07-04 18:15 UTC, provokateurin commented
You only changed the PR title, not the commit message. Also please don't mention the issue, you can just put it in the PR description to refer to the issue.

2024-07-04 19:08 UTC, provokateurin commented
Please checkout the issues the CI found. You can run `melos run format` to fix the formatting problems, but the analyzer issues need to be fixed as well.

2024-07-05 17:50 UTC, provokateurin requested changes

2024-07-05 17:50 UTC, provokateurin commented on packages/neon/neon_notifications/lib/src/widgets/notification.dart
> +        onLongPress: onDelete,
So now we have two ways to delete the notification? That's a bit strange UX wise and

2024-07-05 17:50 UTC, provokateurin commented on packages/neon/neon_notes/lib/src/widgets/notes_view.dart
>              bloc.deleteNote(note.id);
I Just looked closer at the docs of Dismissible and the action itself should be done in onDismissed and not in confirmDismiss.

2024-07-05 17:50 UTC, provokateurin commented on packages/neon/neon_news/lib/src/widgets/folders_view.dart
> +      confirmDismiss: (direction) async {
onDismissed

2024-07-05 17:50 UTC, provokateurin commented on packages/neon/neon_news/lib/src/widgets/feeds_view.dart
> +        confirmDismiss: (direction) async {
onDismissed

2024-07-05 17:50 UTC, provokateurin commented on packages/neon/neon_news/lib/src/widgets/articles_view.dart
> +        confirmDismiss: (direction) async {
onDismissed

2024-07-16 14:44 UTC, provokateurin approved these changes

2024-07-16 15:39 UTC, merged