Fix semanticsLabel for Nextcloud client logo
nextcloud/neon pull request #2283
Opened 2024-07-17 11:56 UTC by Apocalypse96

# Issue -> https://github.com/nextcloud/neon/issues/2273
## Fix Incorrect Semantics Label for Nextcloud Logo

**Issue:** The `semanticsLabel` for the Nextcloud logo was incorrectly transcribed as "Nextcloud logo". This needed to be updated for better accessibility and accuracy.

**Changes Made:**

- Updated the `semanticsLabel` in the `app_implementation.dart` file to provide a more accurate description.

2024-07-17 12:01 UTC, Leptopoda requested changes

2024-07-17 12:01 UTC, Leptopoda commented on packages/neon_framework/lib/src/models/app_implementation.dart
> +            semanticsLabel: "Nextcloud Client Logo",
Thanks for working on this issue but this is not what we need.
The problem is that these pictures contain the logo of the application in question. 
For example this is the files or news icon you can see in the drawer.

I think this should rather use `name(context)`.

2024-07-17 12:02 UTC, Leptopoda commented
And as with your previous PR you'll have to 
- signoff the commit
- use a conventional commit message (something like "fix(neon_framework): semanticsLabel for drawer icon"
- add a unit test to avoid future regressions

2024-07-21 13:15 UTC, provokateurin commented
Closing for now, please re-open if you plan to follow up to the review comments.

2024-07-21 13:15 UTC, closed without merging