fix(nextcloud)!: make news getRead and oldestFirst parameter a boolean
nextcloud/neon pull request #2324
Opened 2024-07-27 19:53 UTC by Leptopoda

2024-07-27 19:59 UTC, provokateurin requested changes
The first commit is wrong because booleans in query parameters are represented as 0/1 in Nextcloud. If the parameters were sent in the body then they could need to be booleans indeed.

2024-07-27 19:59 UTC, provokateurin commented on packages/nextcloud/test/news_test.dart
Would be nice to group the tests by subclients (like it is done in all other tests)

2024-07-27 20:04 UTC, Leptopoda commented on packages/nextcloud/test/news_test.dart
I also thought about it (or even have a separate dart file) but didn't do it for better reviewability.
I can do it as a separte commit.

2024-07-27 20:05 UTC, Leptopoda commented
> The first commit is wrong because booleans in query parameters are represented as 0/1 in Nextcloud. If the parameters were sent in the body then they could need to be booleans indeed.

Can you please clarify that? The docs say that it's meant to be a boolean:
https://nextcloud.github.io/news/api/api-v1-3/#initial-sync
And judging from the code that's the right thing
https://github.com/nextcloud/news/blob/350eea3aa1c62d0ccc18b522bed27a3bb13b208e/lib/Controller/ItemApiController.php#L61

2024-07-27 20:21 UTC, provokateurin commented
Yes, but the documentation shows a JSON body as the example which we don't make use of here.
You can see the old quirk the openapi-extractor had when it still used query paramters: https://github.com/nextcloud/openapi-extractor/commit/826eaf299f23cfcbb6507f5589bcdccab13225ff#diff-ab3a3d862e1786c66098dfc9cba0909b72dbdf080660a1e971ac7851157b2bb8L80
I don't know the location where this is implemented on the server side, but my guess would be that it is within Symfony.
I have no better explanation that this, it's just how it works :woman_shrugging:

2024-07-28 06:59 UTC, Leptopoda commented
I don't know where you see a json body

> /items?type=3&getRead=false&batchSize=-1

But if you say so ...

2024-07-28 07:01 UTC, provokateurin commented
The docs must be wrong there, only 0/1 work

2024-07-28 08:16 UTC, Leptopoda commented on packages/nextcloud/test/news_test.dart
I decided to do this in a followup.

2024-07-28 08:19 UTC, provokateurin approved these changes

2024-07-28 08:19 UTC, provokateurin commented on .vscode/settings.json
Unintended change?

2024-07-28 12:14 UTC, Leptopoda commented on packages/nextcloud/test/news_test.dart
See #2325

2024-07-28 12:41 UTC, merged