perf(nextcloud_test_presets): Use docker image digests to improve caching
nextcloud/neon pull request #2464
Opened 2024-09-04 05:01 UTC by provokateurin

Locally it helps docker a lot to detect that images didn't change and it should also help in CI to avoid unnecessary build time.
The only downside is that we get more preset updates, but it's not too often and the benefits outweigh this downside.

2024-09-04 12:17 UTC, Leptopoda requested changes

2024-09-04 12:17 UTC, Leptopoda commented on packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/app_release.dart
> +              serverRelease.version < maximumServerVersion.incrementMajor(),
With the server release being a separate class this should be a method in there. Maybe something like `bool isInRange(ServerRelease other)`.

2024-09-04 12:17 UTC, Leptopoda commented on packages/nextcloud/packages/nextcloud_test_presets/lib/src/generate_presets.dart
> +    File('${serverPresetsDir.path}/${serverRelease.version.major}.${serverRelease.version.minor}')
The `"$major.$minor"` thing should also be moved into the class (maybe a getter called preset).

2024-09-04 12:17 UTC, Leptopoda commented on packages/nextcloud/packages/nextcloud_test_presets/lib/src/generate_presets.dart
> +    final buffer = StringBuffer()..writeln('SERVER_VERSION=${serverRelease.version}@${serverRelease.digest}');
Also used multiple times.

Mabe a getter called `dockerTag`

2024-09-04 16:26 UTC, provokateurin commented on packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/server_release.dart
> +typedef ServerRelease = ({Version version, String digest});
built_value makes no sense as we never update properties after creation, so final fields are fine and other than a toString() method no serialization is necessary.

2024-09-05 08:09 UTC, Leptopoda approved these changes

2024-09-05 08:40 UTC, merged