Feat/sort box/multi sorting
nextcloud/neon pull request #591
Opened 2023-08-19 16:22 UTC by Leptopoda

based on #590

I applied the requested changes from #585 and also some Dart3 cleanups.
Is the documentation enough?

2023-08-19 16:25 UTC, provokateurin commented
Parts of https://github.com/nextcloud/neon/pull/590 also sneaked in here, please remove :)

2023-08-19 16:48 UTC, Leptopoda commented
That's intnetional as I'll just drop the commit once the other one is merged.

To lazy to resolve conflicts twice :)
Review on the rest should be unaffected.

2023-08-19 17:13 UTC, provokateurin commented
Ah right, I already approved the other one so please go ahead and merge&rebase.

2023-08-24 20:11 UTC, Leptopoda commented
@provokateurin ping :)

2023-08-25 06:10 UTC, provokateurin requested changes

2023-08-25 06:10 UTC, provokateurin commented on packages/sort_box/lib/sort_box.dart
> +  /// Constrcuts a new SortBox.
```suggestion
  /// Constructs a new SortBox.
```

2023-08-25 06:10 UTC, provokateurin commented on packages/sort_box/lib/sort_box.dart
> +  /// A mapping of values [T] to thier *Boxes*.
```suggestion
  /// A mapping of values [T] to their *Boxes*.
```

2023-08-25 06:10 UTC, provokateurin commented on packages/sort_box/lib/sort_box.dart
> +  /// The Boxes are applied if two elements are considered equal regarding thier property [T].
```suggestion
  /// The Boxes are applied if two elements are considered equal regarding their property [T].
```

2023-08-25 06:10 UTC, provokateurin commented on packages/sort_box/lib/sort_box.dart
> +  /// Sorts the [input] list according to thier [box].
```suggestion
  /// Sorts the [input] list according to their [box].
```

2023-08-25 11:38 UTC, provokateurin approved these changes
One last nit pick

2023-08-25 11:38 UTC, provokateurin commented on packages/sort_box/lib/sort_box.dart
> +  /// A mapping of all values [T] to thier [ComparableGetter].
```suggestion
  /// A mapping of all values [T] to their [ComparableGetter].
```

2023-08-25 11:39 UTC, Leptopoda commented on packages/sort_box/lib/sort_box.dart
> +  /// A mapping of all values [T] to thier [ComparableGetter].
Yeah lots of copy :spaghetti:

2023-08-25 12:07 UTC, merged