Feat/neon files/sort folders
nextcloud/neon pull request #604
Opened 2023-08-25 15:49 UTC by Leptopoda

- sort folders first (not configurable)
- hide hidden files (configurable)
- cleanup of some widgets

2023-08-25 17:45 UTC, provokateurin requested changes
I would be nice to have a warning that shows up when you create a hidden file or folder but you have hidden files not shown. Otherwise the user might get confused why the file/folder was not created.

2023-08-25 17:45 UTC, provokateurin commented on packages/neon/neon_files/lib/widgets/file_list_tile.dart
> +  // When the ETag is null it means we are uploading this file right now
Comment should be one line below

2023-08-29 16:29 UTC, Leptopoda commented
What about doing the warning as a followup (maybe together with https://github.com/nextcloud/neon/issues/535)?

It would currently require adding  the warning to two separate dialogs (folder creation and rename dialog). And I think we should first unify them and them

2023-08-29 18:09 UTC, Leptopoda commented
Ah forgot to push one sec

2023-08-30 17:55 UTC, merged