Refactor/dynamite/codestyle
nextcloud/neon pull request #694
Opened 2023-09-01 16:44 UTC by Leptopoda

2023-09-01 18:28 UTC, Leptopoda commented
It's still far from perfect but I think it's already a lot cleaner.

If you don't like the helper methods on the models we can use extension methods for them.

2023-09-02 08:01 UTC, Leptopoda commented
It's gonna be hard to review I know; sorry in advance.
I didn't have any plans and I just found more motivation to clean it up more and more.

The only behavior change should be unifying the method order and style of `anyOf`s and the normal objects.

---

The generation time also went down from 45s to 35s (just the build_runner without any further fixing and formatting)

2023-09-02 08:37 UTC, provokateurin requested changes
Super awesome cleanup! :heart:

I think we should settle on a style/indentation for the inline code. We could align the whole code to the left and remove the extra indentation from the real code around it. I'm not sure if that will look good, but it would at least be unified and easier to handle if the code indentation changes later on.

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/models/operation.dart
> +  Iterable<String> get formatedDescription sync* {
```suggestion
  Iterable<String> get formattedDescription sync* {
```

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/models/schema.dart
> +  Iterable<String> get formatedDescription => descriptionToDocs(description);
```suggestion
  Iterable<String> get formattedDescription => descriptionToDocs(description);
```

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/models/tag.dart
> +  Iterable<String> get formatedDescription => descriptionToDocs(description);
```suggestion
  Iterable<String> get formattedDescription => descriptionToDocs(description);
```

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/helpers/typeresult.dart
File should be named `type_result.dart`

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                  const Code(');'),
Can you change this to a single object? This is really not readable :sweat_smile:

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                        '''),
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                          ''');
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                              ''');
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                              ''');
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                                  ''');
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                                  ''');
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +                                  ''');
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/client.dart
> +          );
Indentation is off

2023-09-02 08:37 UTC, provokateurin commented on packages/dynamite/dynamite/lib/src/builder/header_serializer.dart
> +              ]);
This could also be converted into a single object to make it more readable.

2023-09-02 18:34 UTC, Leptopoda commented
is this how you imagined it?

2023-09-02 18:35 UTC, provokateurin commented
Yes, perfect :)

2023-09-02 18:40 UTC, provokateurin approved these changes

2023-09-02 19:36 UTC, merged