WIP: support date and date-time formats
nextcloud/neon pull request #749
Opened 2023-09-09 05:30 UTC by Leptopoda

This is going to be needed for cookbook support.
I had this on a branch from march and thought it's time :)

I also plan to implement the `base64` `byte` format and an option for custom formats.
I plan to add a config option to dynamites build-yaml config (or a separate file) that can specify:
- string with the import directive
- name of the custom serializer
- serialization method
- deserialization method

This would enable us to have custom formats like `unix-time` or iso 8601 duration support (the later also being needed by cookbook).

I do not plan to implement it without tests though as I can see those features not being used all to frequesntly

2023-10-23 14:49 UTC, Leptopoda commented
now that we have the dynamite e2e tests we can confidently merge this one.

2023-10-23 15:01 UTC, provokateurin requested changes
PR title is wrong

2023-10-23 15:01 UTC, provokateurin commented on packages/dynamite/dynamite_end_to_end_test/test/date_time_test.dart
> +      'date': '2023-10-22T22:00:00.000Z',
```suggestion
      'date': '2023-10-22',
```
According to https://swagger.io/docs/specification/data-models/data-types/

2023-11-08 10:41 UTC, Leptopoda commented
I'll close this for now and tackle this after we have the first releases.
I already have implemented a custom date class with custom serialization locally.

2023-11-08 10:41 UTC, closed without merging