refactor(deps): Pin all dependencies to the lowest possible versions
nextcloud/neon pull request #937
Opened 2023-10-06 09:04 UTC by provokateurin

Closes https://github.com/nextcloud/neon/issues/932

Local renovate run confirms this works.

2023-10-06 10:02 UTC, Leptopoda requested changes
Maybe we should keep the dev dependencies at their current versions.

They shouldn't affect devs using our packages.

2023-10-06 10:02 UTC, Leptopoda commented on packages/nextcloud/pubspec.yaml
> +  built_value_generator: ^8.0.0
We'll need at least 8.5 for the string interpolation issue I fixed upstream
https://pub.dev/packages/built_value_generator/changelog#850

2023-10-06 10:04 UTC, provokateurin commented
Ah I forgot to run all the build_runner things, so maybe I need to raise some constraints again

2023-10-06 10:05 UTC, provokateurin commented
I think we should run `melos exec flutter pub downgrade` before running any of the linting and tests. That way we can ensure that our constraints work fine and we are not running on bad versions.

2023-10-06 13:11 UTC, provokateurin commented
> I think we should run melos exec flutter pub downgrade before running any of the linting and tests. That way we can ensure that our constraints work fine and we are not running on bad versions.

This doesn't work, because other packages have broken dependency constraints that break us. We can't do anything about that, so we need to be careful around this. Though now we have the minimums figured out once, we just need to only upgrade when needed.

2023-10-06 15:26 UTC, provokateurin commented on docs/dependencies.md
> +4. To validate that our version constraints are correct, we run our linting and tests against the lowest dependency versions that are allowed by our constraints.
Ah forgot to remove that again

2023-10-07 12:50 UTC, Leptopoda reviewed
I think we can still keep the dependencies of `App` pinned to the latest.
Similar to the root package as this won't be published.

In theory this doesn't change anything as we update the lockfile anyways but reading the pubspec.yaml is easier than the lockfile.

2023-10-07 12:56 UTC, provokateurin commented
I'm not sure how easy it is to configure that in renovate.
I would argue we can drop the constraints completely, since we want to use the versions that are selected by the constraints of the other packages and we don't want to affect the constraint resolving :thinking:

2023-10-07 14:40 UTC, Leptopoda commented
Sounds like a good idea; Let's try this.

2023-10-07 23:02 UTC, Leptopoda approved these changes

2023-10-08 07:16 UTC, merged