Refactor package .gitignores and .metadatas
nextcloud/neon pull request #971
Opened 2023-10-15 17:25 UTC by provokateurin

Closes https://github.com/nextcloud/neon/issues/797

2023-10-15 20:15 UTC, Leptopoda requested changes
Please also add the step of symlinking the gitignore to our docs:
https://github.com/nextcloud/neon/blob/main/docs/workflows.md

2023-10-15 20:15 UTC, Leptopoda commented on .gitignore
> +
Please also add `packages/**/doc/api` as I ran `dart doc` quite a few times when writing #745

2023-10-15 20:37 UTC, provokateurin commented
There is no symlinking involved because I moved everything into a single top level .gitignore. I will add to the workflows that you need to remove the generated .gitignore from the package.

2023-10-16 06:23 UTC, Leptopoda approved these changes

2023-10-16 06:25 UTC, merged