fix(neon_files): empty browser view
nextcloud/neon pull request #984
Opened 2023-10-17 20:37 UTC by Leptopoda

How didn't we realize that the files view was broken :thinking: 
I think this was introduced with the NeonListView rework.

2023-10-17 20:38 UTC, Leptopoda commented
Ok there is still a bug with moving a file

2023-10-17 20:43 UTC, Leptopoda commented
Ok should be working now.
@provokateurin please take the time to test file moving, folder selection, and both in conjunction with the hidden option.

I hope I didn't miss anything this time.

2023-10-19 06:03 UTC, provokateurin requested changes

2023-10-19 06:03 UTC, provokateurin commented on packages/neon/neon_files/lib/widgets/browser_view.dart
> +                  files.data?.removeWhere((final file) {
This doesn't work correctly when you enable the option again because the hidden files were removed from the data.

2023-10-19 06:07 UTC, provokateurin requested changes

2023-10-19 06:07 UTC, provokateurin commented on packages/neon/neon_files/lib/widgets/browser_view.dart
> +                    }
I think this should respect the hidden option as well. This is how it normally works in any file manager I know.

2023-10-19 12:28 UTC, Leptopoda commented
While being at it I also fixed two other things :)

2023-10-19 13:37 UTC, provokateurin approved these changes

2023-10-19 13:44 UTC, merged